version: '3.8'

services:
  # Spring Boot Application Service
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: shopbackend1
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      
  # PostgreSQL Service
  db:
    image: postgres:15
    container_name: shop_db1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres_admin1
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db


volumes:
  postgres_data: